{
 "title": "Bagman's Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active connection count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(active_connections_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total message sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(total_messages_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "c4d63d739acd05cefa3ead48f4e93328",
     "serviceName": "bagman"
    }
   ]
  }
 ]
}